In [2]:
print(3)

3


In [5]:
import os
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 'data.json',
 'exercise.py',
 'main.py',
 'pr1.py',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'testing.ipynb',
 'venv',
 '__pycache__']

In [7]:
import pandas

In [8]:
df1=pandas.read_csv("supermarkets.csv")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [9]:
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [10]:
python exercise.py

SyntaxError: invalid syntax (Temp/ipykernel_9952/1181037104.py, line 1)

In [15]:
import pandas as pd
list2loop =['a','b','c','d']


for each_item in list2loop:
    execfile("exercise.py")

NameError: name 'execfile' is not defined

In [27]:
df2=pandas.DataFrame(%run exercise.py)

SyntaxError: invalid syntax (Temp/ipykernel_9952/2800453221.py, line 1)

In [38]:
df2=pandas.read_csv("supermarkets.csv")
df2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [33]:
pandas.read_csv?

In [43]:
df2

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [45]:
df2.loc["2":"4","City":"Country"]

City             State Country
ID                                         
2   San Francisco          CA 94119     USA
3   San Francisco  California 94114     USA
4   San Francisco          CA 94114     USA

In [50]:
df2.loc["1":"6","State":"State"]

State
ID                  
1           CA 94114
2           CA 94119
3   California 94114
4           CA 94114
5         California
6           CA 94114

In [51]:
df2.drop(df2.columns[0:3],1)

C:\Users\DELL01~1\AppData\Local\Temp/ipykernel_9952/3399190309.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df2.drop(df2.columns[0:3],1)


Country         Name  Employees
ID                                
1      USA      Madeira          8
2      USA  Bready Shop         15
3      USA  Super River         25
4      USA   Ben's Shop         10
5      USA      Sanchez         12
6      USA   Richvalley         20

In [52]:
df2

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [53]:
df2["continent"]=df2.shape[0]*["INDIA"]

In [54]:
df2

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees continent  
ID                       
1           8     INDIA  
2          15     INDIA  
3          25     INDIA  
4          10     INDIA  
5          12     INDIA  
6          20     INDIA

In [56]:
df2["continent"]="BHARAT-"+"INDIA"
df2

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees     continent  
ID                           
1           8  BHARAT-INDIA  
2          15  BHARAT-INDIA  
3          25  BHARAT-INDIA  
4          10  BHARAT-INDIA  
5          12  BHARAT-INDIA  
6          20  BHARAT-INDIA

In [58]:
df2_t["7"]=["jaipur","jaipur","RJ","India","Gaurav","1","BHARAT-INDIA"]
df2

NameError: name 'df2_t' is not defined

In [3]:
import pandas as pd
df=pd.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [4]:
from geopy.geocoders import ArcGIS

In [5]:
nom=ArcGIS()
n=nom.geocode("Jaipur,INDIA")
n

Location(Jaipur, Rajasthan, (26.925760000000025, 75.80661000000003, 0.0))

In [8]:
nom.geocode("Jaipur,INDIA").latitude()


TypeError: 'float' object is not callable

In [9]:
type(n)

geopy.location.Location

In [10]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [11]:
df["Address"]=df["Address"]+","+df["City"]+","+df["State"]+","+df["Country"]

In [12]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [71]:
df["Coordinates"]=df["Address"].apply(nom.geocode)
df["Coordinates"][1][-1][1]


-122.4253730300932

In [27]:
import os
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 'data.json',
 'exercise.py',
 'main.py',
 'pr1.py',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'testing.ipynb',
 'venv',
 'WhatsApp Image 2021-07-19 at 15.19.15.jpeg',
 '__pycache__']

In [24]:
import numpy
n=numpy.arange(27)

In [26]:
n.reshape([3,3,3])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
import cv2
im_grv=cv2.imread("new.png",1)
im_grv

array([[[197, 197, 197],
        [138, 138, 138],
        [122, 122, 122],
        [130, 130, 130],
        [137, 137, 137]],

       [[179, 179, 179],
        [152, 152, 152],
        [255, 255, 255],
        [219, 219, 219],
        [172, 172, 172]],

       [[213, 213, 213],
        [130, 130, 130],
        [255, 255, 255],
        [138, 138, 138],
        [161, 161, 161]]], dtype=uint8)

In [33]:
cv2.imwrite("new.png",im_grv)

True

In [37]:
im_grv[0][0][0]=179
im_grv

array([[[179, 197, 197],
        [138, 138, 138],
        [122, 122, 122],
        [130, 130, 130],
        [137, 137, 137]],

       [[179, 179, 179],
        [152, 179, 152],
        [255, 255, 255],
        [219, 219, 219],
        [172, 172, 172]],

       [[213, 213, 213],
        [130, 130, 130],
        [255, 255, 255],
        [138, 138, 138],
        [161, 161, 161]]], dtype=uint8)

In [43]:
import folium
mp=folium.Map(location=[80,-100])
mp.save("Map1.html",zoom_start=6)

In [44]:
%run mapping.py

Exception: File `'mapping.py'` not found.

In [47]:
import os
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 'data.json',
 'exercise.py',
 'main.py',
 'Map1.html',
 'mapping.py',
 'new.png',
 'pr1.py',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'testing.ipynb',
 'venv',
 'Volcanoes.txt',
 'WhatsApp Image 2021-07-19 at 15.19.15.jpeg',
 '__pycache__']

In [14]:
%run "mapping.py"

In [3]:
import pandas
df=pandas.read_csv("Volcanoes.txt")
df

VOLCANX020    NUMBER            NAME       LOCATION  \
0        509.0  1201-01=           Baker  US-Washington   
1        511.0  1201-02-    Glacier Peak  US-Washington   
2        513.0  1201-03-         Rainier  US-Washington   
3        515.0  1201-05-      St. Helens  US-Washington   
4        516.0  1201-04-           Adams  US-Washington   
..         ...       ...             ...            ...   
57       580.0  1210-03-  Valles Caldera  US-New Mexico   
58       581.0  1209-02-   Sunset Crater     US-Arizona   
59       584.0  1203-20-           Amboy  US-California   
60       586.0  1210-02-    Zuni-Bandera  US-New Mexico   
61       588.0  1210-01-       Carrizozo  US-New Mexico   

                   STATUS    ELEV             TYPE TIMEFRAME        LAT  \
0              Historical  3285.0  Stratovolcanoes        D3  48.776798   
1        Tephrochronology  3213.0    Stratovolcano        D4  48.111801   
2        Dendrochronology  4392.0    Stratovolcano        D3  46.869801   
3              Historical  2549.0    Stratovolcano        D1  46.199799   
4        Tephrochronology  3742.0    Stratovolcano        D6  46.205799   
..                    ...     ...              ...       ...        ...   
57  Pleistocene-Fumarolic  3430.0          Caldera         Q  35.869999   
58       Dendrochronology  2447.0      Cinder cone        D6  35.369999   
59               Holocene   288.0      Cinder cone         U  34.549999   
60           Anthropology  2550.0   Volcanic field        D7  34.799999   
61               Holocene  1731.0      Cinder cone         U  33.780102   

           LON  
0  -121.810997  
1  -121.111000  
2  -121.751000  
3  -122.181000  
4  -121.490997  
..         ...  
57 -106.570999  
58 -111.501000  
59 -115.780998  
60 -108.001000  
61 -105.931000  

[62 rows x 10 columns]